name: build-image

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-push-timesketch-image:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker/release/build
